"use client"

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Progress } from "@/components/ui/progress"
import { Calendar, TrendingUp, Star } from "lucide-react"

interface WeeklyReportProps {
  reportId: string
}

export function WeeklyReport({ reportId }: WeeklyReportProps) {
  // Mock data - replace with real AI-generated report data
  const reportData = {
    period: "January 8-14, 2024",
    totalEntries: 6,
    totalWords: 2847,
    averageMood: 7.8,
    topThemes: ["personal growth", "work challenges", "gratitude"],
    keyInsights: [
      "You showed remarkable resilience when dealing with work challenges this week",
      "Your gratitude practice is becoming more consistent and detailed",
      "There's a growing focus on personal development and learning",
    ],
    moodTrend: "improving",
    writingConsistency: 85,
  }

  return (
    <div className="space-y-6">
      {/* Report Header */}
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle className="flex items-center gap-2">
                <Calendar className="w-5 h-5" />
                Weekly Summary
              </CardTitle>
              <CardDescription>{reportData.period}</CardDescription>
            </div>
            <Badge variant="default" className="bg-green-500">
              Generated by AI
            </Badge>
          </div>
        </CardHeader>
        <CardContent>
          <div className="grid md:grid-cols-4 gap-6">
            <div className="text-center">
              <div className="text-2xl font-bold text-primary">{reportData.totalEntries}</div>
              <div className="text-sm text-muted-foreground">Journal Entries</div>
            </div>
            <div className="text-center">
              <div className="text-2xl font-bold text-primary">{reportData.totalWords}</div>
              <div className="text-sm text-muted-foreground">Words Written</div>
            </div>
            <div className="text-center">
              <div className="text-2xl font-bold text-primary">{reportData.averageMood}/10</div>
              <div className="text-sm text-muted-foreground">Average Mood</div>
            </div>
            <div className="text-center">
              <div className="text-2xl font-bold text-primary">{reportData.writingConsistency}%</div>
              <div className="text-sm text-muted-foreground">Consistency</div>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Key Insights */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Star className="w-5 h-5 text-yellow-500" />
            Key Insights This Week
          </CardTitle>
          <CardDescription>AI-identified patterns and observations</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            {reportData.keyInsights.map((insight, index) => (
              <div key={index} className="flex items-start gap-3 p-4 bg-muted/50 rounded-lg">
                <div className="w-2 h-2 bg-primary rounded-full mt-2 flex-shrink-0" />
                <p className="text-sm leading-relaxed">{insight}</p>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* Themes and Patterns */}
      <div className="grid lg:grid-cols-2 gap-6">
        <Card>
          <CardHeader>
            <CardTitle>Top Themes</CardTitle>
            <CardDescription>Most discussed topics this week</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              {reportData.topThemes.map((theme, index) => (
                <div key={theme} className="flex items-center justify-between">
                  <span className="text-sm capitalize">{theme}</span>
                  <Badge variant="outline">{Math.floor(Math.random() * 5) + 3} mentions</Badge>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <TrendingUp className="w-5 h-5 text-green-500" />
              Progress Indicators
            </CardTitle>
            <CardDescription>Your growth metrics this week</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <span className="text-sm">Mood Stability</span>
                <span className="text-sm font-medium">Excellent</span>
              </div>
              <Progress value={88} className="h-2" />
            </div>
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <span className="text-sm">Self-Reflection Depth</span>
                <span className="text-sm font-medium">High</span>
              </div>
              <Progress value={75} className="h-2" />
            </div>
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <span className="text-sm">Goal Orientation</span>
                <span className="text-sm font-medium">Improving</span>
              </div>
              <Progress value={65} className="h-2" />
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
